services:
  db:
    image: postgres:17.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: route
    volumes:
      - ./base.sql:/docker-entrypoint-initdb.d/base.sql
    ports:
      - "5432:5432"
  app:
    build:
      context: ./route
    depends_on:
      - db
    ports:
      - "8080:8080"
  # carte:
  #   build:
  #     context: ./carte
  #   ports:
  #     - "3000:3000"