version: "3.8"

services:
  app:
    build: .
    container_name: java_app
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    depends_on:
      - postgres
      - tileserver
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/projet_route
      SPRING_DATASOURCE_USERNAME: toky
      SPRING_DATASOURCE_PASSWORD: toky

  postgres:
    image: postgres:16
    container_name: postgres_route
    restart: always
    environment:
      POSTGRES_DB: projet_route
      POSTGRES_USER: toky
      POSTGRES_PASSWORD: toky
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  tileserver:
    image: maptiler/tileserver-gl
    container_name: tileserver_route
    restart: always
    ports:
      - "8081:8080"
    volumes:
      - ./docker/tileserver/data:/data
    command: >
      tileserver-gl
      --import /data/madagascar-latest.osm.pbf
      --port 8080

volumes:
  postgres_data:
